### ISSUE TITLE
Can't add AWS MFA secret

### ISSUE THREAD

**Issue by jans23** [Nitrokey/nitrokey-pro-firmware#22]
The original ticket is here: https://github.com/Nitrokey/nitrokey-app/issues/26

**Comment by szszszsz** [comment]
To sum up: issue is caused by storage limitations and needs it's structure redesign.

**Comment by tripleclones** [comment]
Can you give any time frames on this please?

Just to clarify I have experienced more services using longer secret keys which are incompatible other then AWS

**Comment by jans23** [comment]
No time frame yet. Which are these other services you are mentioning?

>

**Comment by szszszsz** [comment]
Current TOTP secret given by AWS is 64 base32 characters which is 40 bytes (320 bits).

**Comment by tripleclones** [comment]
VPS provider Bitfolk is the one that springs to mind but I'm sure there was another as well, I will check some other providers I use

**Comment by jans23** [comment]
We are going to tailor our devices to AWS's secret length. It would be
important, how long the secrets of those other providers is and if such
exceed the secret's length AWS is using.

>

**Comment by tripleclones** [comment]
When I set up AWS I was given a 64 Byte key. Bitfolk provided a 80 Byte key. As I understand it the Nitrokey is current limited to 32 Bytes?

**Comment by szszszsz** [comment]
Hi! @tripleclones
Could you tell, are these bytes encoded base32, base64 or hex? Are there any information of their type? I guess the first, but wanted to confirm.

**Comment by tripleclones** [comment]
I appears to be base32 yes, although I have asked the question to be sure.

**Comment by tripleclones** [comment]
Confirmed 50 bytes base32 encoded

**Comment by tripleclones** [comment]
OK so Bitfolk have drop the requirements of their key to fit in with the current 32 base32 - so its just AWS now :)

**Comment by szszszsz** [comment]
The AWS OTP keys will be supported from now on Nitrokey Pro v0.8 and hopefully on Nitrokey Storage next versions (v0.44+).
