### ISSUE TITLE
Update security

### ISSUE THREAD

**Issue by samuel3d1** [Nitrokey/nitrokey-pro-firmware#41]
Hi,

I am looking for some information about the security of the update mechanism for nitrokey.

Here is one of the questions that come to mind after learning about the possibility to m do firmware updates:

What measures will prevent an aversary to flash a manipulated firmware to the nitrokey. Assuming an aversary has gained access to my system, I want nitrokey to prevent them from getting my privat keys and data. If the firmware can be manipulated, I don't see how this can be effectively prevented.

**Comment by jans23** [comment]
The firmware of the Nitrokey Pro can't be updated. Firmware updates of Nitrokey Start and Nitrokey Storage are password protected.
