### ISSUE TITLE
HOTP size 20 bytes vs Nitrokey storage of 40 bytes. Hardware limitation?

### ISSUE THREAD

**Issue by tlaurion** [Nitrokey/nitrokey-pro-firmware#59]
Was wondering if it was a hardware limitation of the pro version or if that code could also benefit the pro: https://github.com/Nitrokey/nitrokey-storage-firmware/commit/ec5c0c13076a2064da330ee9bb6206dccaadee71

_Sent from my Galaxy S3 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by szszszsz** [comment]
Hi!

Pro has 40 bytes (320 bits) HOTP secrets since v0.8 AFAIR. Storage with
this extension will be released next week.

sob., 27.04.2019, 05:38 użytkownik tlaurion <notifications@github.com>
napisał:

**Comment by szszszsz** [comment]
Closing as question. Storage related ticket: https://github.com/Nitrokey/nitrokey-storage-firmware/pull/85.
