### ISSUE TITLE
Regarding the “SmartCard-HSM generates weak AES Keys” on Nitrokey HSM2

### ISSUE THREAD

**Issue by pachulo** [Nitrokey/nitrokey-pro-firmware#67]
I've read this: 

- https://www.smartcard-hsm.com/2019/09/17/generate-symmetric-key-bug.html

And was guessing which options do the owners of a Nitrokey HSM2 have to update the firmware/solve it.

Thanks!

**Comment by jans23** [comment]
https://support.nitrokey.com/t/security-advice-smartcard-hsm-generates-weak-aes-keys/1948
-- 
Sent from a mobile device.
